default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  database: test_guru_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
