default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["PSQL_USER"] %>
  password: <%= ENV["PSQL_PASS"] %>
  host: <%= ENV["PSQL_HOST"] %>

development:
  <<: *default
  database: <%= ENV["PSQL_DB"]%>

test:
  <<: *default
  database: test_guru_test

production:
  <<: *default
  database: test_guru_production
